# Generated by Django 2.2.17 on 2021-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0003_auto_20210311_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=200),
        ),
    ]
