# Generated by Django 2.2.17 on 2021-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0004_auto_20210312_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
