# Generated by Django 2.2.17 on 2021-03-16 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0006_university_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_title', models.CharField(max_length=50)),
                ('rev_text', models.CharField(max_length=750)),
                ('rev_rating', models.IntegerField()),
                ('rev_upvotes', models.IntegerField(default=0)),
                ('rev_downvotes', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CourseRate.Modules')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
