# Generated by Django 2.2.17 on 2021-03-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rev_rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=30),
        ),
    ]
