# Generated by Django 2.2.17 on 2021-03-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0008_auto_20210317_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
