# Generated by Django 2.2.17 on 2021-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0009_departments_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
