# Generated by Django 2.2.17 on 2021-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0010_modules_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='unique_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='departments',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='modules',
            name='slug',
            field=models.SlugField(),
        ),
    ]
