# Generated by Django 2.2.17 on 2021-04-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseRate', '0011_auto_20210331_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='unique_slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
